name: Generate ASCII Artwork

on:
  push:

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List repo Files
        run: ls -larth
      - name: Executing shell script
        run: |
         chmod u+x ./script.sh
         ./script.sh
      - name: Upload the generated file or artifact to be used in other jobs
        uses: actions/upload-artifact@v4
        with:
            name: dragon-text-file
            path: dragon.txt
      - name: Display structure of downloaded files
        run: ls -R
       

  test_job:
    needs:  build_job
    runs-on: ubuntu-latest
    steps:
      - name: Downloading the file from buil job
        uses: actions/download-artifact@v4
        with:
            name: dragon-text-file
      - name: Check file generated in the build stage
        run: grep -i "dragon" dragon.txt

  deploy_job:
    runs-on: ubuntu-latest
    needs: test_job
    steps:
      - name: Downloading the file from buil job
        uses: actions/download-artifact@v4
        with:
            name: dragon-text-file
      - name: read file
        run: cat dragon.txt
      - name: Deploy
        run: echo "Deployment ongoing..."