name: Generate ASCII Artwork

on:
  push:

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List repo Files
        run: ls -larth
      - name: Executing shell script
        run: |
         chmod u+x ./script.sh
         ./script.sh
      - name: Sleep for 30 secons
        run: sleep 30

  test_job:
    needs:  build_job
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 10 secons
        run: sleep 10

      - name: Check file generated in the build stage
        run: grep -i "dragon" dragon.txt

  deploy_job:
    runs-on: ubuntu-latest
    needs: test_job
    steps:
      - name: read file
        run: cat dragon.txt
      - name: Deploy
        run: echo "Deployment ongoing..."