name: Generate ASCII Artwork

on:
  push:

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List repo Files
        run: ls -larth
      - name: Executing shell script
        run: ./script.sh
